import PrivyAuthProvider from '@/components/providers/PrivyAuthProvider';

import { Roboto_Mono } from 'next/font/google';

import Header from './components/Header';

import './globals.css';

import type { Metadata } from 'next';

const robotoMono = Roboto_Mono({
  preload: true,
  weight: ['400', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
  fallback: ['PingFang SC', 'Microsoft YaHei', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={robotoMono.className}
    >
      <body>
        <PrivyAuthProvider>
          <Header />

          <div
            className="container"
            style={{
              maxWidth: '1200px',
              margin: '0 auto',
              padding: '24px',
            }}
          >
            {children}
          </div>
        </PrivyAuthProvider>
      </body>
    </html>
  );
}
